[default.probe]
protocol = "Swd"
usb_vid = "0d28"
usb_pid = "0204"
serial = "99063602000528209568F418DEE859A0000000006E052820"

[default.general]
chip = "nrf52833_xxAA"  # micro:bit V2

[default.reset]
halt_afterwards = false

[default.rtt]
enabled = true

[default.gdb]
enabled = false
